language: python
python:
- '3.5'
- '3.6'
install:
- pip install --upgrade pip
- pip install .[test]
- pip install .[doc]
script: pytest
notifications:
  slack:
    rooms:
    - lcmap:UTqlh9PfPVomfpli10WKyZoh#cicd
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  distributions: sdist bdist_wheel
  on:
    repo: USGS-EROS/lcmap-merlin
    branch: master
